id: AAEA1BB7F
base_file: f803A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:22:59.541184
  last_modified_at: 2022-05-30 18:22:59.541192
